name: "Lint Markdown"

# El workflow se dispara en cada push o pull_request [cite: 20]
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  markdown-lint:
    name: "Execute Markdown Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Run Markdownlint"
        uses: davidanson/markdownlint-cli2-action@v16
        with:
          config: '.markdownlint.json'
          globs: '**/*.md'